### ISSUE TITLE
[TECHNICAL] Server-side sync of members data

### ISSUE THREAD

**Issue by Dr-Wade** [bcc-code/bcc-online#7]
One big part of the firebase cloud functions is syncing of members data. We currently do this in a middleware, using data from the JWT Token for the sync. A server-side sync of all the members data would be a better option

**Comment by andreasgan** [comment]
@KillerX you did this now right?

**Comment by KillerX** [comment]
Correct. Not as described (we sync 1x per week when you make an api request) and hope to move to WebHooks when they are available in members.
