### ISSUE TITLE
[BUG] Login fails when user changes auth0 account

### ISSUE THREAD

**Issue by Dr-Wade** [bcc-code/bcc-online#8]
We've experienced that login on BCC Online doesn't work after a user changes their account in auth0 (we don't know for which reason this happens).

BCC Online has its own database of users for authentication, with the following structure: "${personId}@person.id" as email address and their auth0 id as identifier
BCC Online gives back "Email already exists on another account".

**Comment by KillerX** [comment]
This seems to have been resolved as a side effect to some changes in the auth processing.
